name: Update WordPress Version on EKS

on:
  push:
    branches:
      - main

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read WordPress version from file
      id: read_version
      run: |
        version=$(grep WORDPRESS_VERSION values.txt | cut -d '=' -f2)
        echo "version=$version" >> "$GITHUB_OUTPUT"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name demo-nodeport --region us-east-1

    - name: Add Bitnami Helm repository
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update   

    - name: Upgrade WordPress with new version
      run: |
        helm upgrade my-wordpress bitnami/wordpress \
          --set service.type=NodePort \
          --set image.repository=bitnami/wordpress \
          --set image.tag=${{ steps.read_version.outputs.version }}
          --set mariadb.primary.persistence.enabled=false \
          --set persistence.enabled=false
